### ISSUE TITLE
bug: build fail in ios platform

### ISSUE THREAD

**Issue by yeikel16** [Mietz-GmbH/flutter_electronicid#5]
When I run the example on an iPhone 12 (emulator) I get the following error.

```sh
Launching lib/main.dart on iPhone 12 in debug mode...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Removing script build phase dependency analysis.
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Flutter
      - flutter_electronicid
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_electronicid` from `.symlinks/plugins/flutter_electronicid/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_d_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/a/d/c/VideoIDSDK/1.2.0/VideoIDSDK.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/a/d/c/VideoIDSDK/1.2.0/VideoIDSDK.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_9_7_8.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/7/8/eIDRTC/1.1.35/eIDRTC.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_1_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/1/d/lottie-ios/4.1.3/lottie-ios.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_e_d_6.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/e/d/6/OpenSSL-Universal/1.1.1900/OpenSSL-Universal.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "lottie-ios":
      In snapshot (Podfile.lock):
        lottie-ios (= 3.2.3)
      In Podfile:
        flutter_electronicid (from `.symlinks/plugins/flutter_electronicid/ios`) was resolved to 1.4.0, which depends on
          VideoIDSDK (= 1.2.0) was resolved to 1.2.0, which depends on
            lottie-ios (= 4.0.0)
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `lottie-ios` inside your development pod `flutter_electronicid`.
       You should run `pod update lottie-ios` to apply changes you've made.
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
    /Users/yeikel/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    /Users/yeikel/.gem/bin/pod:25:in `load'
    /Users/yeikel/.gem/bin/pod:25:in `<main>'
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 12.
Exited

```

I run  `pod repo update` or with `pod install --repo-update` but not work for me

**Comment by yeikel16** [comment]
Apparently it is a bug in the dependency of `lottie-ios 4.0.0` when using `git-lfs`

https://github.com/airbnb/lottie-ios/issues/1830

I was able to solve the problem by installing it `brew install git-lfs`
